### ISSUE TITLE
Could you write the implementation steps in more detail?

### ISSUE THREAD

**Issue by yuzi0537** [leihui6/LRBO#1]
Can you write the implementation steps in more detail? The current instructions are not very accurate to follow, for example, 
"b. You can train your own model using (if you have a robot base other than UR3e, UR5 and UR5e) 
python main.py configs/train/indoor.yaml" 
There is no main.py and configs directory here

**Comment by yuzi0537** [comment]
the link in the "the robot base datasets can be downloaded from here" is not working.
There is no "datasets.indoor" and "IndoorDataset"

**Comment by leihui6** [comment]
HI yuzi,

Thank you for your attention. 😊

The ```main.py``` was provided from the [OverlapPredator](https://github.com/prs-eth/OverlapPredator). We follow the 3DMatch to train so that you can refer to the [section. Train](https://github.com/prs-eth/OverlapPredator?tab=readme-ov-file#train).
